.TH DCALC 1  "25 Oct 2001" "" "Commands"
.SH NAME
dcalc \- a financial, statistics, scientific & programmers calculator
.SH SYNOPSIS
.nf
.B dcalc
.PP
.SH DESCRIPTION
.B dcalc 
is a financial, statistics, scientific and programmers
calculator for curses under Unix and Linux.
.PP
It uses Reverse Polish Notation (HP-style).
.PP
There is another version of this for the Psion (RPN only) at:
http://sedumi.freeshell.org/psion
.PP
This is about as much of a manual that I feel like writing - if you
want to know more about RPN calculators (and why they are more
intuitive than algebraic calculators with their = sign) take a
look at http://www.hpcalc.org
.PP
Have fun with it! Bob Hepple: mailto:bhepple@freeshell.org
.SH "RETURN VALUE"
.B dcalc
returns 0
.SH "ENVIRONMENT VARIABLES"
.TP
Nothing pertinent.
.SH "BUGS"
Please report to the email address above
.\" For emacs: 
.\" Local Variables: 
.\" fill-column: 70 
.\" eval:(setq filename (substring buffer-file-name (string-match "[a-zA-Z0-9_.]+$" buffer-file-name))) 
.\" eval:(setq basename (substring filename 0 (string-match "\\." filename))) 
.\" eval:(setq compile-command (concat "nroff " filename " -t -man >../cat3/" basename ".3")) 
.\" End: 
